import type {
  AxiosResponse,
  InternalAxiosRequestConfig,
} from "axios";
import type { SessionUser } from "@/context/AuthProvider";
import type {
  AccountStatistics,
  CreditBalanceProps,
  CreditTransactionProps,
  NotificationCountProps,
  PlanProps,
  ProjectProps,
} from "@/types";

export const isMockMode =
  process.env.NEXT_PUBLIC_MOCK_AUTH === "true" &&
  process.env.NODE_ENV !== "production";

export const MOCK_USER: SessionUser = {
  uid: "mock-user",
  email: "mock@alphadrafts.com",
  fullName: "Mock User",
  roles: ["user", "subscriber"],
  emailVerified: true,
};

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 86_400_000).toISOString();
const daysAhead = (days: number) =>
  new Date(Date.now() + days * 86_400_000).toISOString();

const makeProject = (
  overrides: Partial<ProjectProps> &
    Pick<ProjectProps, "id" | "name" | "type" | "status">,
): ProjectProps => ({
  userId: MOCK_USER.uid,
  description: "A sample project generated by local mock mode.",
  content:
    "<p>This is a sample document generated by local mock mode. It exists so the editor and check flow can be previewed without a backend.</p><p>Replace this content with your own when you connect a real backend.</p>",
  dueDate: daysAhead(14),
  progress: 0,
  stage: 0,
  rating: 0,
  createdAt: daysAgo(7),
  updatedAt: daysAgo(1),
  ...overrides,
});

export const mockProjects: ProjectProps[] = [
  makeProject({
    id: "mock-project-1",
    name: "Marketing Content Audit",
    type: "report",
    status: "completed",
    progress: 100,
    stage: 4,
    rating: 4.5,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  }),
  makeProject({
    id: "mock-project-2",
    name: "AI Originality Review",
    type: "essay",
    status: "draft",
    progress: 40,
    stage: 2,
    rating: 3,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
  }),
  makeProject({
    id: "mock-project-3",
    name: "Research Paper Draft",
    type: "research_paper",
    status: "draft",
    progress: 75,
    stage: 3,
    rating: 4,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(3),
  }),
  makeProject({
    id: "mock-project-4",
    name: "Case Study Analysis",
    type: "case_study",
    status: "completed",
    progress: 100,
    stage: 4,
    rating: 5,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(4),
  }),
  makeProject({
    id: "mock-project-5",
    name: "Thesis Chapter 2",
    type: "thesis",
    status: "draft",
    progress: 10,
    stage: 1,
    rating: 2,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(0),
  }),
];

export const mockProjectHistory = {
  data: mockProjects,
  totalCount: mockProjects.length,
};

export const mockSubscription = {
  currentPlan: "free" as const,
  freeChecksUsed: 2,
  lastFreeCheckResetDate: daysAgo(2),
};

export const mockCreditBalance: CreditBalanceProps = {
  available: 2500,
  used: 500,
  monthlyAllocation: 3000,
  lastUpdated: daysAgo(0),
};

export const mockStatistics: AccountStatistics = {
  memberSince: daysAgo(90),
  totalAnalysisResult: 12,
  totalEvaluations: 8,
  totalProjects: mockProjects.length,
  totalAnalysisResults: 12,
  totalWordsWritten: 12500,
};

export const mockNotificationCount: NotificationCountProps = {
  total_count: 0,
  unread_count: 0,
};

export const mockPlans: PlanProps[] = [
  {
    productId: "mock-plan-free",
    name: "Free",
    amount: 0,
    description: "3 AI checks per month",
    benefits: [{ name: "3 checks per month" }],
    priceId: "mock-price-free",
    currency: "USD",
    interval: "month",
    checksPerMonth: 3,
  },
  {
    productId: "mock-plan-pay-per-check",
    name: "Pay-Per-Check",
    amount: 500,
    description: "Buy credits that never expire",
    benefits: [{ name: "Credits never expire" }],
    priceId: "mock-price-pay-per-check",
    currency: "USD",
    interval: "one_time",
  },
  {
    productId: "mock-plan-subscription",
    name: "Subscription",
    amount: 950,
    description: "40,000 monthly credits",
    benefits: [{ name: "40,000 credits per month" }],
    priceId: "mock-price-subscription",
    currency: "USD",
    interval: "month",
    monthlyCredits: 40000,
  },
];

const mockCreditHistoryEntry = (
  id: string,
  transactionId: string,
  type: CreditTransactionProps["type"],
  amount: number,
  description: string,
  createdAt: string,
): CreditTransactionProps => ({
  id,
  userId: MOCK_USER.uid,
  transactionId,
  type,
  totalCredit: amount,
  balance: 2500,
  status: "completed",
  amount,
  description,
  source: "mock",
  createdAt,
  updatedAt: createdAt,
});

export const mockCreditHistory = {
  data: [
    mockCreditHistoryEntry(
      "mock-credit-1",
      "mock-tx-1",
      "purchase",
      2000,
      "Credit purchase",
      daysAgo(5),
    ),
    mockCreditHistoryEntry(
      "mock-credit-2",
      "mock-tx-2",
      "usage",
      500,
      "AI Originality check",
      daysAgo(1),
    ),
  ],
  totalCount: 2,
  hasMore: false,
};

export const mockSubscriptionHistory = {
  data: [
    mockCreditHistoryEntry(
      "mock-sub-1",
      "mock-tx-3",
      "allocation",
      3000,
      "Monthly free plan allocation",
      daysAgo(2),
    ),
  ],
  totalCount: 1,
  hasMore: false,
};

const getPathname = (config: InternalAxiosRequestConfig): string => {
  const url = config.url ?? "";
  const withoutHost = url.replace(/^https?:\/\/[^/]+/, "");
  return withoutHost.split("?")[0] ?? "";
};

const findProjectById = (id: string) =>
  mockProjects.find(project => project.id === id) ?? mockProjects[0];

const singleResourceId = (
  pathname: string,
  prefix: string,
): string | null => {
  if (!pathname.startsWith(`${prefix}/`)) return null;
  const rest = pathname.slice(prefix.length + 1);
  if (!rest || rest.includes("/")) return null;
  return rest;
};

const resolveGetPayload = (pathname: string): unknown => {
  const v2ProjectId = singleResourceId(pathname, "/v2/projects");
  if (v2ProjectId) return findProjectById(v2ProjectId);

  if (pathname === "/v2/projects") return mockProjectHistory;

  const v1ProjectId = singleResourceId(pathname, "/v1/projects");
  if (v1ProjectId) return findProjectById(v1ProjectId);

  if (pathname === "/v1/projects") return mockProjectHistory;
  if (pathname === "/v1/payments/subscription") return mockSubscription;
  if (pathname === "/v1/credits/balance") return mockCreditBalance;
  if (pathname.startsWith("/v1/credits/history")) return mockCreditHistory;
  if (pathname.startsWith("/v1/users/subscription-history"))
    return mockSubscriptionHistory;
  if (pathname === "/v1/users/statistics") return mockStatistics;
  if (pathname === "/v1/users/notifications/notifications-count")
    return mockNotificationCount;
  if (pathname === "/v1/payments/plans") return mockPlans;

  return {};
};

export const mockRequest = (
  config: InternalAxiosRequestConfig,
): AxiosResponse => {
  const method = (config.method ?? "get").toLowerCase();
  const pathname = getPathname(config);
  const payload = method === "get" ? resolveGetPayload(pathname) : {};

  return {
    data: { status: "success", message: "OK", code: 200, data: payload },
    status: 200,
    statusText: "OK",
    headers: {},
    config,
    request: {},
  };
};
